/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsDealIdRouteImport } from './routes/deals.$dealId'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealIdRoute = DealsDealIdRouteImport.update({
  id: '/$dealId',
  path: '/$dealId',
  getParentRoute: () => DealsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deals': typeof DealsRouteWithChildren
  '/saved': typeof SavedRoute
  '/stores': typeof StoresRoute
  '/deals/$dealId': typeof DealsDealIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deals': typeof DealsRouteWithChildren
  '/saved': typeof SavedRoute
  '/stores': typeof StoresRoute
  '/deals/$dealId': typeof DealsDealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deals': typeof DealsRouteWithChildren
  '/saved': typeof SavedRoute
  '/stores': typeof StoresRoute
  '/deals/$dealId': typeof DealsDealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/deals' | '/saved' | '/stores' | '/deals/$dealId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/deals' | '/saved' | '/stores' | '/deals/$dealId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/deals'
    | '/saved'
    | '/stores'
    | '/deals/$dealId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DealsRoute: typeof DealsRouteWithChildren
  SavedRoute: typeof SavedRoute
  StoresRoute: typeof StoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealId': {
      id: '/deals/$dealId'
      path: '/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof DealsDealIdRouteImport
      parentRoute: typeof DealsRoute
    }
  }
}

interface DealsRouteChildren {
  DealsDealIdRoute: typeof DealsDealIdRoute
}

const DealsRouteChildren: DealsRouteChildren = {
  DealsDealIdRoute: DealsDealIdRoute,
}

const DealsRouteWithChildren = DealsRoute._addFileChildren(DealsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DealsRoute: DealsRouteWithChildren,
  SavedRoute: SavedRoute,
  StoresRoute: StoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
